-- Ported from hyprland.conf (hyprlang) to Lua config format.
-- Hyprland's Lua config API surface is documented via the EmmyLua stub at
-- /usr/share/hypr/stubs/hl.meta.lua -- point your editor's lua-language-server
-- at that file (or symlink it into this directory's workspace) for full
-- autocomplete + type checking on every hl.* call below. See also:
-- https://wiki.hypr.land/Configuring/Start/

-- - [ ] prob split this into multiple files based on purpose / wiki category
--       (the Lua config supports this natively via require("myFile") -- see
--       the "MY PROGRAMS" section below for where that would start paying off)
-- https://www.reddit.com/r/hyprland/comments/1jp47lx/a_modular_hyprland_configuration_a_kickstart_for/

-- claude suggested enhancement (prob. due after improving nvim lsp setup): Get lua-language-server pointed at /usr/share/hypr/stubs/hl.meta.lua

-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/
-- exec-once entries now live inside an hl.on("hyprland.start", ...) callback.
-- The old `exec-once = [workspace 1] cmd` syntax becomes hl.exec_cmd(cmd, { workspace = "1" }).

hl.on("hyprland.start", function()
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("uwsm app -- waybar")
    -- hl.exec_cmd("uwsm app -- syncthing") -- replaced with systemd user service

    -- setup everdo API host 1st, then launch
    -- if changing everdo path / filename here, also change in .config/shell/aliasrc & desktop file (/usr/share/applications/everdo.desktop)
    -- hl.exec_cmd("/home/sujal/.config/shell/evrd-addr && /home/sujal/.local/bin/Everdo-1.11.15.AppImage", { workspace = "1" })
    -- hl.exec_cmd("/home/sujal/.config/shell/evrd-addr && /home/sujal/.local/bin/everdo-1.11.6-early-access.AppImage", { workspace = "1" })
    hl.exec_cmd("mindwtr", { workspace = "1" })
    -- hl.exec_cmd([[emacs --eval "(progn (org-agenda nil \"d\") (delete-other-windows))"]], { workspace = "1" })
    -- this requires emacs user service to be enabled
    -- hl.exec_cmd([[emacsclient -c -e "(progn (org-agenda nil \"d\") (delete-other-windows))"]], { workspace = "1" })
    hl.exec_cmd("uwsm app -- wlsunset -S 07:30 -s 17:40")
    hl.exec_cmd("clipse -listen")
    hl.exec_cmd("uwsm app -- sane-break")
    -- hl.exec_cmd([[uwsm app -- bash -c "sleep 3 && sane-break"]]) -- ensure this runs after waybar initialized
    -- hl.exec_cmd("uwsm app -- qbittorrent")
    -- for laptop mic, use port that doesn't have static noise
    -- TODO: currently has issues with muting @DEFAULT_AUDIO_SOURCE not working properly. fix someday
    -- can pass 54(id for Microphone) like so: wpctl set-mute 54 toggle
    -- but not really suitable since it isn't set as default & waybar doesn't reflect changes

    -- hl.exec_cmd("pactl set-default-source alsa_input.pci-0000_03_00.6.analog-stereo && pactl set-source-port alsa_input.pci-0000_03_00.6.analog-stereo analog-input-mic")
    -- hl.exec_cmd("pactl set-source-port alsa_input.pci-0000_03_00.6.analog-stereo analog-input-mic")
end)


-- ###########################################################################
-- The legacy `# AUTOGENERATED HYPRLAND CONFIG` banner + `autogenerated = 0`
-- keyword from the old .conf don't have a Lua equivalent -- that warning was
-- specific to the hyprlang autogen marker and doesn't apply to Lua configs.
-- ###########################################################################

-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")


------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/

-- single monitor (laptop)
-- hl.monitor({ output = "eDP-1", mode = "1366x768@60", position = "0x0", scale = 1 })

-- dual monitor home setup
hl.monitor({ output = "HDMI-A-1", mode = "preferred",     position = "0x0",    scale = 1 })
hl.monitor({ output = "eDP-1",    mode = "1366x768@60",   position = "1366x0", scale = 1 })

-- screen mirroring setup
-- hl.monitor({ output = "eDP-1",    mode = "preferred", position = "0x0",  scale = 1 })
-- hl.monitor({ output = "HDMI-A-1", mode = "preferred", position = "auto", scale = 1, mirror = "eDP-1" })
-- hl.monitor({ output = "HDMI-A-1", mode = "1920x1080@60", position = "auto", scale = 1, mirror = "eDP-1" })

-- projector setup (w/ laptop display as main and projector as secondary)
-- hl.monitor({ output = "eDP-1",    mode = "preferred", position = "0x0",  scale = 1 })
-- hl.monitor({ output = "HDMI-A-1", mode = "preferred", position = "auto", scale = 1 })

-- disable laptop monitor
-- hl.monitor({ output = "eDP-1", disabled = true })


---------------------
---- MY PROGRAMS ----
---------------------

-- See https://wiki.hypr.land/Configuring/Keywords/

-- Set programs that you use
local terminal    = "ghostty"
local browser     = "waterfox"
local fileManager = "nautilus"
-- make uwsm run apps launched through wofi as separate units
-- otherwise, issue may arise when running apps in same systemd unit as compositor
-- NOTE: the --define part is necessary
local menu = "uwsm app -- $(wofi --show drun --allow-images --define=drun-print_desktop_file=true)"
-- local menu = [[uwsm app -- "$(wofi --show drun --allow-images --define=drun-print_desktop_file=true | sed -E "s/(\.desktop) /\1:/")"]]
local borderSize = 1
local rounding   = 0


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/

-- https://wiki.hypr.land/Configuring/Basics/Variables/#general
hl.config({
    general = {
        gaps_in         = 0,
        gaps_out        = 0,
        gaps_workspaces = 50,

        border_size = borderSize,

        -- see https://wiki.hypr.land/Configuring/Basics/Variables/#variable-types for info about colors
        col = {
            active_border   = "rgba(33ccffee)",
            inactive_border = "rgba(595959aa)",
        },

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = true,

        -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
        allow_tearing = false,

        layout = "master",

        snap = {
            -- enabled = true,
        },
    },

    decoration = {
        rounding = rounding,

        -- Change transparency of focused and unfocused windows
        active_opacity   = 1.0,
        inactive_opacity = 1.0,
        dim_inactive     = false,
        dim_strength     = 0.15,

        shadow = {
            enabled      = false,
            range        = 4,
            render_power = 3,
            color        = "rgba(1a1a1aee)",
        },

        -- https://wiki.hypr.land/Configuring/Basics/Variables/#blur
        blur = {
            enabled  = false,
            size     = 1,
            passes   = 1,
            vibrancy = 0.16,
        },
    },

    cursor = {
        no_warps            = true,
        no_hardware_cursors = 1,
    },
})

-- https://wiki.hypr.land/Configuring/Basics/Variables/#animations
hl.config({
    animations = {
        enabled = true, -- yes, please :)
    },
})

-- Default animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/ for more
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })

hl.animation({ leaf = "global",        enabled = true,  speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true,  speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true,  speed = 4.79, bezier = "easeOutQuint" })
hl.animation({ leaf = "windowsIn",     enabled = true,  speed = 4.1,  bezier = "easeOutQuint", style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true,  speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true,  speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true,  speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true,  speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true,  speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true,  speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true,  speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true,  speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true,  speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = false })
hl.animation({ leaf = "workspacesOut", enabled = false })
-- hl.animation({ leaf = "workspacesIn",  enabled = true, speed = 1.21, bezier = "almostLinear", style = "slide" })
-- hl.animation({ leaf = "workspacesOut", enabled = true, speed = 1.94, bezier = "almostLinear", style = "slide" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.

hl.window_rule({
    name  = "fullscreen-border-color",
    match = { fullscreen = true },
    border_color = "rgb(999999)",
})

-- center window if there is only 1 window in a tiling workspace
-- maybe this should be named rule if you want effects to be reverted when condition no longer met?
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = "0 130" })

-- no outer gaps for ws1 (everdo)
-- hl.workspace_rule({ workspace = "1", gaps_out = 0 })
-- remove gaps in fullscreen (useful when passing 1 to fullscreen)
-- currently has bug where rounding isn't reset upon toggling fullscreen for floating windows
-- hl.workspace_rule({ workspace = "f[1]", gaps_out = 0, gaps_in = 0, no_rounding = true })

-- make windows in scratchpad (special) float by default
hl.window_rule({
    name  = "special-workspace",
    match = { workspace = "s[1]" },
    float = true,
    size   = "monitor_w*0.8 monitor_h*0.8",
    center = true,
})

-- obsidian settings window floats at scratchpad size
hl.window_rule({
    name  = "obsidian-settings",
    match = { class = "obsidian", title = "^Settings" },
    float  = true,
    size   = "monitor_w*0.8 monitor_h*0.8",
    center = true,
})

hl.workspace_rule({ workspace = "special:magic", on_created_empty = terminal })
-- hl.workspace_rule({ workspace = "2", on_created_empty = browser })

-- open workspaces 1 & 2 on ext. monitor
hl.workspace_rule({ workspace = "1", monitor = "HDMI-A-1", default = true })
hl.workspace_rule({ workspace = "2", monitor = "HDMI-A-1" })

-- hl.workspace_rule({ workspace = "5", monitor = "m[1]" }) -- unclear original intent ("m[1]"), left untranslated

-----------------------------
---- PICTURE IN PICTURE ----
-----------------------------

-- firefox Picture-in-Picture
-- No `size` here on purpose -- Firefox already sizes the PiP window to match the
-- video's own aspect ratio (varies per video), so forcing a fixed box would
-- fight that. persistent_size just remembers whatever you drag it to afterward,
-- instead of re-snapping to some default on every new PiP window. keep_aspect_ratio
-- doesn't lock it to 16:9 or anything -- it locks to whatever ratio the window
-- currently has, so dragging one edge scales the other proportionally instead of
-- letting you stretch/squish the video while resizing.
hl.window_rule({
    name  = "pip-firefox",
    match = { title = "^(Picture-in-Picture)$" },
		-- persistent_size   = true,
    keep_aspect_ratio = true,
    pin   = true,
    move  = "monitor_w-window_w monitor_h-window_h",
    float = true,
    -- don't focus PiP window when it spawns
    no_initial_focus = true,
    suppress_event   = "activate activatefocus",
})

-- ff2mpv (yt videos played via mpv from firefox) -- same PiP treatment as
-- firefox's native PiP. ff2mpv-rust config (~/.config/ff2mpv-rust.json) sets
-- --wayland-app-id=ff2mpv so this matches on app class, not title (mpv's
-- title is the video title, which varies).
hl.window_rule({
    name  = "pip-ff2mpv",
    match = { class = "^(ff2mpv)$" },
    keep_aspect_ratio = true,
    pin   = true,
    move  = "monitor_w-window_w monitor_h-window_h",
    float = true,
    no_initial_focus = true,
    suppress_event   = "activate activatefocus",
})

-- Tried to keep pinned PiP windows below the scratchpad (special:magic)
-- overlay via alter_zorder -- doesn't work. Pinned windows always render on
-- top of everything, including the special workspace, regardless of
-- z-order; confirmed live (toggled scratchpad + alter_zorder bottom on the
-- pinned window, it stayed on top; unpinning just made it disappear from
-- the current workspace's view entirely instead, since unpinned windows
-- only show on their own workspace). Seems to be a Hyprland limitation, not
-- a config mistake -- worth a discussion upstream.

-- hide sensitive windows during screenshare
-- bitwarden doesn't work cause it sets title late. new hyprland says title bug only happens for 'static' effects & no_screen_share isn't one of them, but still doesn't work
-- dunst doesn't work because class only set on X11?
hl.window_rule({
    name  = "hide-sensitive-from-screenshare",
    match = { class = "^(Emacs|Dunst|com\\.clipse|Bitwarden)$" },
    no_screen_share = true,
})

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
-- hl.config({
--     dwindle = {
--         pseudotile     = true, -- Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
--         preserve_split = true, -- You probably want this
--     },
-- })

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
    master = {
        new_status = "slave",
    },
})

-- https://wiki.hypr.land/Configuring/Basics/Variables/#misc
hl.config({
    misc = {
        force_default_wallpaper   = 1,    -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo     = true, -- If true disables the random hyprland logo / anime girl background. :(
        disable_splash_rendering  = true,
        enable_swallow            = true,
        -- add other programs to regex with | separator
        swallow_regex             = "^(com\\.mitchellh\\.ghostty)$",

        -- swallow_exception_regex = "^(.*wev.*|.*xkbcli.*|)$",
        -- swallow_exception_regex = "^(wev.*|swayimg.*)$",
        focus_on_activate           = true,
        on_focus_under_fullscreen   = 2,
        -- exit_window_retains_fullscreen = true,

        middle_click_paste = false,
    },
})


---------------
---- INPUT ----
---------------

-- https://wiki.hypr.land/Configuring/Basics/Variables/#input
hl.config({
    input = {
        kb_layout  = "us",
        kb_variant = "",
        kb_model   = "",
        -- commented out because caps binds are handled by kanata, which is cross-platform
        -- kb_options = "caps:none", -- for using caps+WASD as arrow keys on Redragon
        -- kb_options = "ctrl:nocaps", -- use caps as ctrl, but issues w/ Caps + WASD on Redragon keeb
        kb_options = "",
        kb_rules   = "",

        follow_mouse = 1,

        sensitivity        = -0.04, -- -1.0 - 1.0, 0 means no modification.
        scroll_button_lock = true,
        accel_profile      = "adaptive",
        repeat_delay       = 280,

        touchpad = {
            natural_scroll = true,
            scroll_factor  = 0.22,
            drag_lock      = 0, -- set to 0 to disable, 1 for remove lock after timeout
        },

        tablet = {
            output = "current",
        },
    },

    binds = {
        workspace_back_and_forth = true,
        -- lets a pinned window (PiP: firefox/ff2mpv, mainMod+P ad-hoc) go
        -- properly fullscreen -- e.g. mpv's own "f" key. Off by default in
        -- Hyprland, which is why pressing f in a PiP mpv window silently did
        -- nothing before this.
        allow_pin_fullscreen = true,
    },

    debug = {
        disable_logs = true,
    },
})

-- https://wiki.hypr.land/Configuring/Advanced-and-Cool/Gestures/
hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })
-- hl.gesture({ fingers = 3, direction = "down", mods = "ALT", action = "close" })
hl.gesture({ fingers = 3, direction = "up", action = "fullscreen" })
hl.gesture({ fingers = 3, direction = "down", scale = 0.5, action = "float" })

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
    name        = "epic-mouse-v1",
    sensitivity = -0.5,
})


---------------------
---- KEYBINDINGS ----
---------------------

-- See https://wiki.hypr.land/Configuring/Basics/Binds/
local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hypr.land/Configuring/Basics/Binds/ for more
hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))
-- hl.bind(mainMod .. " + Escape", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + SHIFT + C", hl.dsp.window.close())                -- close window
hl.bind(mainMod .. " + SHIFT + M", hl.dsp.exit())                        -- exit hyprland
-- mode 1 = maximize, matches old .conf's `fullscreen, 1`. Intent: fill screen
-- but keep waybar visible + apps' own chrome (e.g. Firefox address bar).
-- Currently broken upstream on 0.56.2 -- maximize geometry ignores waybar's
-- reserved area regardless of mode. Tracked: github.com/hyprwm/Hyprland/discussions/14531
hl.bind(mainMod .. " + F",         hl.dsp.window.fullscreen({ mode = "maximized"}))
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd(browser))
hl.bind(mainMod .. " + Space", hl.dsp.exec_cmd(menu))

-- hl.bind(mainMod .. " + slash", hl.dsp.exec_cmd("hyprctl dispatch toggleswallow"))
hl.bind(mainMod .. " + slash", hl.dsp.window.toggle_swallow())
-- hl.bind(mainMod .. " + P", hl.dsp.window.pseudo()) -- dwindle
-- PICTURE IN PICTURE (PiP), ad-hoc: turn any window into one, same treatment
-- as the firefox/ff2mpv PiP rules above. One-way: float the focused window,
-- shrink to 32% monitor width (height auto-computed from the window's
-- current aspect ratio, not forced to 16:9), lock aspect ratio, and pin. Not
-- a toggle -- use the existing float-toggle bind (mainMod + SHIFT + F) to
-- send it back to tiled.
hl.bind(mainMod .. " + P", function()
    local win = hl.get_active_window()
    if not win then return end

    local mon = win.monitor or hl.get_active_monitor()
    if not mon then return end

    if not win.floating then
        hl.dispatch(hl.dsp.window.float({ action = "toggle" }))
    end

    local sz   = win.size
    local curW = (sz and (sz.x or sz.w)) or mon.width
    local curH = (sz and (sz.y or sz.h)) or mon.height

    local targetW = mon.width * 0.32
    local targetH = targetW * (curH / curW)

    -- resize's own `keep_aspect_ratio` flag only governs *this* resize call,
    -- it doesn't stick -- dragging the window afterward would let you distort
    -- it, unlike the window-rule-matched PiP windows above, which stay locked
    -- via the persistent `keep_aspect_ratio` property. set_prop sets that same
    -- persistent property here, so ad-hoc PiP behaves the same way. value
    -- must be 1/0 (number) -- a lua boolean errors with "'value' is required".
    hl.dispatch(hl.dsp.window.set_prop({ prop = "keep_aspect_ratio", value = 1, window = win }))
    hl.dispatch(hl.dsp.window.resize({ x = targetW, y = targetH }))

    if not win.pinned then
        hl.dispatch(hl.dsp.window.pin())
    end
end)

-- Free resize (dwm-style): press once, move the mouse (no button held) to
-- resize the focused window live, press the same bind again (or Escape/
-- Enter) to confirm and stop. Hyprland has no native "resize by just moving
-- the mouse" mode -- window.resize/window.drag both require a held mouse
-- button (see the mainMod+RMB bind above) -- so this fakes it with a ~60Hz
-- timer polling the cursor position.
--
-- For floating windows: like dwm's patch, the corner nearest the cursor AT
-- PRESS TIME becomes the anchor -- the opposite corner stays fixed and the
-- grabbed corner follows the mouse, so grabbing near the top-left and
-- moving the mouse left/up grows the window that direction instead of only
-- ever growing right/down. Determined once at press time, not re-evaluated
-- mid-resize (matches the dwm patch).
--
-- For tiled windows there's no "corner" to anchor -- the resize dispatcher
-- just adjusts the layout split -- so it's a plain relative resize there.
--
-- No aspect-ratio unlock/relock needed for PiP windows here, despite them
-- having a persistent `keep_aspect_ratio` lock (see mainMod+P above): tested
-- live, and that lock only constrains *interactive* border-drag resizing --
-- it does nothing to a resize dispatched with an explicit size, which is
-- what this timer loop does every tick. So PiP windows resize freely under
-- this bind regardless of the lock, and dragging their border by hand
-- afterward still respects the lock as before -- no conflict.
--
-- Escape/Enter only exit resize mode -- scoped to the "free_resize" submap
-- so they're only intercepted while it's active, not globally (a plain
-- top-level bind on bare Escape/Enter would swallow those keys everywhere,
-- in every app, all the time). mainMod+R itself stays a normal top-level
-- bind outside the submap, marked submap_universal so it still fires to
-- exit even while the submap has taken over -- otherwise, once a submap is
-- active, only that submap's own binds (or ones explicitly marked
-- universal) respond; the R press would stop doing anything.
local MIN_SIZE = 20
local free_resize = { active = false, win = nil, timer = nil }

local function stop_free_resize()
    free_resize.active = false
    if free_resize.timer then free_resize.timer:set_enabled(false) end
    free_resize.timer = nil
    free_resize.win   = nil
    hl.dispatch(hl.dsp.submap("reset"))
end

hl.define_submap("free_resize", function()
    hl.bind("Escape", stop_free_resize)
    hl.bind("Return", stop_free_resize)
    hl.bind("mouse:272", stop_free_resize) -- left click
    hl.bind("mouse:273", stop_free_resize) -- right click
end)

hl.bind(mainMod .. " + R", function()
    if free_resize.active then
        stop_free_resize()
        return
    end

    local win = hl.get_active_window()
    if not win then return end

    local start = hl.get_cursor_pos()
    if not start then return end

    free_resize.active = true
    free_resize.win    = win

    if win.floating then
        local pos = win.at
        local sz  = win.size
        local baseX, baseY = (pos and (pos.x or pos[1])) or 0, (pos and (pos.y or pos[2])) or 0
        local baseW, baseH = (sz and (sz.x or sz.w)) or 1, (sz and (sz.y or sz.h)) or 1

        -- which half of the window the cursor was in at press time picks
        -- the anchored corner: -1 = anchor follows from the left/top edge,
        -- 1 = grows from the right/bottom edge (the old, simple behaviour)
        local dirX = ((start.x - baseX) / baseW < 0.5) and -1 or 1
        local dirY = ((start.y - baseY) / baseH < 0.5) and -1 or 1

        free_resize.timer = hl.timer(function()
            if not free_resize.active then return end

            local cur = hl.get_cursor_pos()
            if not cur then return end

            local dx = cur.x - start.x
            local dy = cur.y - start.y

            local newW = math.max(MIN_SIZE, baseW + dirX * dx)
            local newH = math.max(MIN_SIZE, baseH + dirY * dy)
            -- when anchored on the left/top, the fixed edge is the opposite
            -- one -- so the window's own x/y has to shift to compensate as
            -- width/height changes, otherwise it'd grow from top-left always
            local newX = (dirX < 0) and (baseX + (baseW - newW)) or baseX
            local newY = (dirY < 0) and (baseY + (baseH - newH)) or baseY

            hl.dispatch(hl.dsp.window.resize({ x = newW, y = newH, window = free_resize.win }))
            hl.dispatch(hl.dsp.window.move({ x = newX, y = newY, window = free_resize.win }))
        end, { type = "repeat", timeout = 16 })
    else
        local last = start
        free_resize.timer = hl.timer(function()
            if not free_resize.active then return end

            local cur = hl.get_cursor_pos()
            if not cur then return end

            local dx = cur.x - last.x
            local dy = cur.y - last.y

            if dx ~= 0 or dy ~= 0 then
                hl.dispatch(hl.dsp.window.resize({ x = dx, y = dy, relative = true, window = free_resize.win }))
            end

            last = cur
        end, { type = "repeat", timeout = 16 })
    end

    hl.dispatch(hl.dsp.submap("free_resize"))
end, { submap_universal = true })

-- hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit")) -- dwindle
-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + H", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + L", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + K", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + J", hl.dsp.focus({ direction = "down" }))

-- simulate alt tab: focus last focused window
hl.bind(mainMod .. " + Tab", hl.dsp.focus({ last = true }))

-- Switch workspaces with mainMod + [0-9]
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key, hl.dsp.focus({ workspace = i }))
end

-- Move active window to a workspace with mainMod + SHIFT + [0-9]
-- (`follow = false` is the "silent" behaviour -- window moves, view stays put)
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i, follow = false }))
end

-- move window to monitor
-- NOTE: this was previously using window.move's `direction` mode, which moves
-- within the tiling layout, not across monitors -- wrong dispatcher mode for
-- what "mon:l silent" meant in the old config. window.move also has a
-- `monitor` mode ({ monitor = "DP-1"|"+"|"-", follow? }), used here with the
-- same "l"/"r" shorthand already relied on below for workspace.move -- verify
-- "l"/"r" resolve the way "+"/"-" would if this doesn't behave.
hl.bind(mainMod .. " + SHIFT + A", hl.dsp.window.move({ monitor = "l", follow = false }))
hl.bind(mainMod .. " + SHIFT + D", hl.dsp.window.move({ monitor = "r", follow = false }))

-- move workspace to monitor (no silent option)
hl.bind(mainMod .. " + A", hl.dsp.workspace.move({ monitor = "l" }))
hl.bind(mainMod .. " + D", hl.dsp.workspace.move({ monitor = "r" }))

-- DWM style swap master
hl.bind(mainMod .. " + Return", hl.dsp.layout("swapwithmaster auto"))

-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + S",         hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e+1" }))

-- screenshots
hl.bind("Print",              hl.dsp.exec_cmd("uwsm app -- hyprshot -m region --clipboard-only"))
hl.bind("SHIFT + Print",      hl.dsp.exec_cmd("uwsm app -- hyprshot -m region -o ~/Pictures/screenshots/"))
hl.bind(mainMod .. " + Print",         hl.dsp.exec_cmd("uwsm app -- hyprshot -m window -m active --clipboard-only"))
hl.bind(mainMod .. " + SHIFT + Print", hl.dsp.exec_cmd("uwsm app -- hyprshot -m window -m active -o ~/Pictures/screenshots/"))
-- this prevents black border around screenshots
hl.layer_rule({ name = "no-anim-hyprpicker", match = { namespace = "hyprpicker" },  no_anim = true })
hl.layer_rule({ name = "no-anim-selection",  match = { namespace = "selection" },   no_anim = true })

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Resize windows
-- NOTE: verify against the wiki -- hl.window.resize's table takes { x, y, relative?, window? }
-- in pixels; the old percent-of-current-size shorthand ("-10% 0") has no confirmed
-- direct equivalent, so these are rough pixel-delta guesses -- tune to taste.
hl.bind(mainMod .. " + SHIFT + H", hl.dsp.window.resize({ x = -100, y = 0,   relative = true }))
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.window.resize({ x = 100,  y = 0,   relative = true }))
hl.bind(mainMod .. " + SHIFT + J", hl.dsp.window.resize({ x = 0,    y = 100, relative = true }))
hl.bind(mainMod .. " + SHIFT + K", hl.dsp.window.resize({ x = 0,    y = -100, relative = true }))

-- NOTE: install playerctl, brightnessctl, and wpctl
-- Laptop multimedia keys for volume and LCD brightness
-- { locked = true } binds are used even while the screen is locked
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"),    { locked = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),    { locked = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),   { locked = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true })
hl.bind("XF86MonBrightnessUp",   hl.dsp.exec_cmd("brightnessctl s 8%+"), { locked = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl s 8%-"), { locked = true })
hl.bind("SHIFT + XF86MonBrightnessUp",   hl.dsp.exec_cmd("brightnessctl s 3%+"), { locked = true })
hl.bind("SHIFT + XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl s 3%-"), { locked = true })

-- replicate above functionality using non-multimedia keys
hl.bind(mainMod .. " + equal",     hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true })
hl.bind(mainMod .. " + minus",     hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true })
hl.bind(mainMod .. " + backspace", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })
hl.bind(mainMod .. " + SHIFT + equal", hl.dsp.exec_cmd("brightnessctl s 8%+"), { locked = true })
hl.bind(mainMod .. " + SHIFT + minus", hl.dsp.exec_cmd("brightnessctl s 8%-"), { locked = true })
hl.bind(mainMod .. " + bracketright", hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind(mainMod .. " + bracketleft",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })
hl.bind(mainMod .. " + backslash",    hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Ignore maximize requests from apps. You'll probably like this.
hl.window_rule({
    name  = "suppress-maximize-events",
    match = { class = ".*" },
    suppress_event = "maximize",
})

-- Fix some dragging issues with XWayland
hl.window_rule({
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },
    no_focus = true,
})

-- Hyprland-run windowrule
hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },
    move  = "20 monitor_h-120",
    float = true,
})

hl.window_rule({
    name    = "ghostty-opacity",
    match   = { class = "com\\.mitchellh\\.ghostty" },
    opacity = "0.88",
})
-- hl.window_rule({ name = "emacs-opacity", match = { class = "Emacs" }, opacity = "0.9" })

-- clipse clipboard manager
-- TODO: need to fix size not being applied
hl.window_rule({
    name   = "clipse-float",
    match  = { class = "(com.clipse)" },
    float  = true,
    center = true,
    size   = "monitor_w*0.25 monitor_h*0.5",
})
hl.window_rule({
    name  = "clipse-stay-focused",
    match = { class = "(com.clipse)" },
    stay_focused = true,
})
hl.bind("SUPER + V", hl.dsp.exec_cmd("ghostty --class=com.clipse -e clipse"))

hl.window_rule({
    name  = "clipboard-float-rules",
    match = { class = "(com.clipse)" },
    float  = true,
    center = true,
    size   = "monitor_w*0.4 monitor_h*0.7",
})

-- requires wl-copy, wl-paste, wtype & rofi (or other menu)
hl.bind(mainMod .. " + period", hl.dsp.exec_cmd("rofimoji -r '' -a type copy"))
hl.bind(mainMod .. " + C",      hl.dsp.exec_cmd("hyprpicker -a"))
